### ISSUE TITLE
Pip install gives error: No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by datavistics** [krzjoa/bace#4]
Im using python 3.6:
```
C:\Users\DT-Laptop\projects\NapkinML>pip install bayes-variants
Collecting bayes-variants
  Using cached bayes-variants-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DT-LAP~1\AppData\Local\Temp\pip-build-zmwrsspi\bayes-variants\setup.py", line 22, in <module>
        with open('requirements.txt') as fid:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\DT-LAP~1\AppData\Local\Temp\pip-build-zmwrsspi\bayes-variants\

```

**Comment by krzjoa** [comment]
It should work now. **bayes-variants** is deprecated in favor of **bace** package :smiley:
